import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import QueryProvider from './lib/QueryProvider'
import {EdgeStoreProvider} from './lib/edgeStoreProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Upload Files Online',
  description: 'Generated by create next app',
}

export default function RootLayout({children} : {children: React.ReactNode}) {
  return (
    <html lang="en">
      <QueryProvider>
        <EdgeStoreProvider>
          <body className={inter.className}>{children}</body>
        </EdgeStoreProvider>
      </QueryProvider>
    </html>
  )
}
